import Head from 'next/head';

export default function Checkout() {
  return (
    <div>
      <Head>
        <title>Astrument</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Checkout</h1>
    </div>
  );
}
